package project2;

import java.math.BigInteger;
import java.util.Random;

/**
 * @author Zolangi Ramirez
 *
 */

public class KeyGen {
	static BigInteger p,q,n,totient;
	
	public static void main(String[] args) {
		Random rnd = new Random();						// random number
		int bitLength = 512;							// recommended bit length for p and q
		p = BigInteger.probablePrime(bitLength, rnd);  	// create p, as a random prime
		q = BigInteger.probablePrime(bitLength, rnd);	// create q, as a random prime
		n = p.multiply(q);								// the size n by p x q 
		System.out.println("p: " + p +"\nq: " + q);
		totient = p.subtract(BigInteger.ONE).multiply(q.subtract(BigInteger.ONE)); // totient function calculated by (p-1)x(q-1) 
		BigInteger e = genE(totient, bitLength, rnd); 	// assign e to value generated by genE()
		BigInteger d = e.modInverse(totient);			// is the inverse of e modulo totient(n)
		
		System.out.println("e: " + e + "\nd: " + d + "\nn: " + n);
	}
	
	// public static void 

	// returns true if the gcd is equal to one, else returns false
	public static boolean gcdIsOne(BigInteger e, BigInteger totient){
		boolean isOne= false;				// boolean to check whether the gcd is one
		
		BigInteger gcd = e.gcd(totient);  	// gcd finds the gcd(e, totient)
		
		System.out.println("The GCD is: " + gcd);
		
		if(gcd.compareTo(BigInteger.ONE) == 0)			// checks if gcd is equal to one
			isOne = true;					//if gcd = 1, then set boolean to true
		else
			isOne = false;
		
		System.out.println("isOne: " + isOne);
		
		return isOne;						// return boolean value
	}
	
	// generates e
	public static BigInteger genE (BigInteger totient, int bitLength, Random rnd){
		BigInteger temp = BigInteger.probablePrime(bitLength, rnd); 	// random prime for temporary use in this method
		
		System.out.println("The temp value of this BigInt is: " + temp);
		System.out.println(temp.compareTo(BigInteger.ONE) == 1);
		System.out.println(temp.compareTo(totient));
		
		
		BigInteger e = null;											// instantiate e
		boolean gcd = gcdIsOne(temp, totient);
		
		System.out.println(gcd);
		
		if((temp.compareTo(BigInteger.ONE) == 1) && temp.compareTo(totient) == -1 && gcd == true ){
			e = temp;
			return e;
		}
		else{
			genE(totient, bitLength, rnd);
		}
		return e;
	}
}
